/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 */
package com.artidev.oeildelynx.domain;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Affaire.class)
public abstract class Affaire_ {

    // Raw attributes
    public static volatile SingularAttribute<Affaire, Integer> id;
    public static volatile SingularAttribute<Affaire, String> libelleAffaire;

    // Many to one
    public static volatile SingularAttribute<Affaire, Localite> codeLocalite;

    // Many to many
    public static volatile ListAttribute<Affaire, Biens> numeroBiens;
    public static volatile ListAttribute<Affaire, Infraction> codeInfactions;
}