/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/Entity.e.vm.java
 */
package com.artidev.oeildelynx.domain;

import static javax.persistence.FetchType.LAZY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.MapsId;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.Objects;

@Entity
@Table(name = "autre_bien")
public class AutreBien implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(AutreBien.class);

    // Raw attributes
    private Integer id;
    private String designationBien;

    // One to one
    private Biens biens;

    // -- [id] ------------------------

    @Override
    @Column(name = "numero_bien", precision = 10)
    @GeneratedValue
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public AutreBien id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [designationBien] ------------------------

    @Size(max = 30)
    @Column(name = "designation_bien", length = 30)
    public String getDesignationBien() {
        return designationBien;
    }

    public void setDesignationBien(String designationBien) {
        this.designationBien = designationBien;
    }

    public AutreBien designationBien(String designationBien) {
        setDesignationBien(designationBien);
        return this;
    }

    // -----------------------------------------------------------------
    // One to one
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // Owner side of one-to-one relation: AutreBien.id ==> Biens.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    @JoinColumn(name = "numero_bien", nullable = false, unique = true)
    @MapsId
    @OneToOne(fetch = LAZY)
    public Biens getBiens() {
        return biens;
    }

    public void setBiens(Biens biens) {
        this.biens = biens;
    }

    public AutreBien biens(Biens biens) {
        setBiens(biens);
        return this;
    }

    /**
     * Apply the default values.
     */
    public AutreBien withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof AutreBien && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this AutreBien instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add(AutreBien_.id.getName(), getId()) //
                .add(AutreBien_.designationBien.getName(), getDesignationBien()) //
                .toString();
    }
}