/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/CompositePk.cpk.vm.java
 */
package com.artidev.oeildelynx.domain;

//import static org.apache.commons.lang.StringUtils.isNotEmpty;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Transient;

import com.google.common.base.Objects;

@Embeddable
public class BiensRecherchesPk implements Comparable<BiensRecherchesPk>, Serializable {
    private static final long serialVersionUID = 1L;

    private Integer numeroBien;
    private Integer numeroRecherche;

    public BiensRecherchesPk() {
    }

    public BiensRecherchesPk(Integer numeroBien, Integer numeroRecherche) {
        this.numeroBien = numeroBien;
        this.numeroRecherche = numeroRecherche;
    }

    /**
     * Helper to determine if this composite primary key is fully set.
     */
    @Transient
    public boolean areFieldsSet() {
        return isNumeroBienSet() && isNumeroRechercheSet();
    }

    /**
     * Helper method to determine if this instance is considered empty, that is,
     * if all the non primary key columns are null.
     */
    @Transient
    public boolean isEmpty() {
        return !isNumeroBienSet() && !isNumeroRechercheSet();
    }

    //-- [numeroBien] ------------------------------

    @Column(name = "numero_bien", nullable = false, precision = 10)
    public Integer getNumeroBien() {
        return numeroBien;
    }

    public void setNumeroBien(Integer numeroBien) {
        this.numeroBien = numeroBien;
    }

    public BiensRecherchesPk numeroBien(Integer numeroBien) {
        setNumeroBien(numeroBien);
        return this;
    }

    /**
     * Helper that determines if this attribute is set or not.
     */
    @Transient
    public boolean isNumeroBienSet() {
        return getNumeroBien() != null;
    }

    //-- [numeroRecherche] ------------------------------

    @Column(name = "numero_recherche", nullable = false, precision = 10)
    public Integer getNumeroRecherche() {
        return numeroRecherche;
    }

    public void setNumeroRecherche(Integer numeroRecherche) {
        this.numeroRecherche = numeroRecherche;
    }

    public BiensRecherchesPk numeroRecherche(Integer numeroRecherche) {
        setNumeroRecherche(numeroRecherche);
        return this;
    }

    /**
     * Helper that determines if this attribute is set or not.
     */
    @Transient
    public boolean isNumeroRechercheSet() {
        return getNumeroRecherche() != null;
    }

    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof BiensRecherchesPk && hashCode() == other.hashCode());
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(getNumeroBien(), getNumeroRecherche());
    }

    @Override
    public int compareTo(BiensRecherchesPk other) {
        return other == null ? -1 : hashCode() - other.hashCode();
    }

    /**
     * Return the string representation of the composite primary key, it should be reversable by version produced by the {@link #String()} method
     */
    @Override
    public String toString() {
        StringBuilder result = new StringBuilder();
        if (isNumeroBienSet()) {
            result.append(getNumeroBien());
        }
        result.append(":");
        if (isNumeroRechercheSet()) {
            result.append(getNumeroRecherche());
        }

        return result.toString();
    }

    /**
     * Build an instance from a string version produced by the {@link #toString()} method
     */
    /*public static BiensRecherchesPk fromString(String string) {
        BiensRecherchesPk result = new BiensRecherchesPk();
        String[] values = string.split(":");
        if (isNotEmpty(values[0])) {
            result.setNumeroBien(Integer.valueOf(values[0]));
        }
        if (isNotEmpty(values[1])) {
            result.setNumeroRecherche(Integer.valueOf(values[1]));
        }

        return result;
    }*/
}
