/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/Entity.e.vm.java
 */
package com.artidev.oeildelynx.domain;

import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.Objects;

@Entity
@Table(name = "biens_recherches", uniqueConstraints = { @UniqueConstraint(name = "pk_biens_recherches", columnNames = { "numero_bien", "numero_recherche" }),
        @UniqueConstraint(name = "biens_recherches_pk", columnNames = { "numero_bien", "numero_recherche" }) })
public class BiensRecherches implements Identifiable<BiensRecherchesPk>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(BiensRecherches.class);

    // Composite primary key
    private BiensRecherchesPk id = new BiensRecherchesPk();

    // Raw attributes
    private String etatBienRecherche;

    // Many to one
    private Biens numeroBien;
    private Recherche numeroRecherche;

    // -----------------------
    // Composite Primary Key
    // -----------------------

    /**
     * Returns the composite primary key.
     */
    @Override
    @EmbeddedId
    public BiensRecherchesPk getId() {
        return id;
    }

    /**
     * Set the composite primary key.
     * @param id the composite primary key.
     */
    @Override
    public void setId(BiensRecherchesPk id) {
        this.id = id;
    }

    public BiensRecherches id(BiensRecherchesPk id) {
        setId(id);
        return this;
    }

    /**
     * Tells whether or not this instance has a non empty composite primary key set.
     * @return true if a non empty primary key is set, false otherwise
     */
    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return getId() != null && getId().areFieldsSet();
    }

    // -- [etatBienRecherche] ------------------------

    @Size(max = 10)
    @Column(name = "etat_bien_recherche", length = 10)
    public String getEtatBienRecherche() {
        return etatBienRecherche;
    }

    public void setEtatBienRecherche(String etatBienRecherche) {
        this.etatBienRecherche = etatBienRecherche;
    }

    public BiensRecherches etatBienRecherche(String etatBienRecherche) {
        setEtatBienRecherche(etatBienRecherche);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: BiensRecherches.numeroBien ==> Biens.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "numero_bien", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    @MapsId(value = "numeroBien")
    public Biens getNumeroBien() {
        return numeroBien;
    }

    /**
     * Set the {@link #numeroBien} without adding this BiensRecherches instance on the passed {@link #numeroBien}
     */
    public void setNumeroBien(Biens numeroBien) {
        this.numeroBien = numeroBien;
    }

    public BiensRecherches numeroBien(Biens numeroBien) {
        setNumeroBien(numeroBien);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: BiensRecherches.numeroRecherche ==> Recherche.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "numero_recherche", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    @MapsId(value = "numeroRecherche")
    public Recherche getNumeroRecherche() {
        return numeroRecherche;
    }

    /**
     * Set the {@link #numeroRecherche} without adding this BiensRecherches instance on the passed {@link #numeroRecherche}
     */
    public void setNumeroRecherche(Recherche numeroRecherche) {
        this.numeroRecherche = numeroRecherche;
    }

    public BiensRecherches numeroRecherche(Recherche numeroRecherche) {
        setNumeroRecherche(numeroRecherche);
        return this;
    }

    /**
     * Apply the default values.
     */
    public BiensRecherches withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof BiensRecherches && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this BiensRecherches instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add(BiensRecherches_.etatBienRecherche.getName(), getEtatBienRecherche()) //
                .toString();
    }
}