/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 */
package com.artidev.oeildelynx.domain;

import java.util.Date;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Condamnation.class)
public abstract class Condamnation_ {

    // Raw attributes
    public static volatile SingularAttribute<Condamnation, Long> id;
    public static volatile SingularAttribute<Condamnation, String> peine;
    public static volatile SingularAttribute<Condamnation, Double> montantAmende;
    public static volatile SingularAttribute<Condamnation, Date> dateCondamanation;

    // Many to one
    public static volatile SingularAttribute<Condamnation, Infraction> codeInfaction;
    public static volatile SingularAttribute<Condamnation, Jugement> codeJugement;
    public static volatile SingularAttribute<Condamnation, Juridiction> codeJuridiction;
    public static volatile SingularAttribute<Condamnation, Affaire> numeroAffaire;
    public static volatile SingularAttribute<Condamnation, Personne> numeroPers;
}