/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/Entity.e.vm.java
 */
package com.artidev.oeildelynx.domain;

import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;
import static javax.persistence.TemporalType.DATE;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.Objects;

@Entity
@Table(name = "condamnation")
public class Condamnation implements Identifiable<Long>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(Condamnation.class);

    // Raw attributes
    private Long id;
    private String peine;
    private Double montantAmende;
    private Date dateCondamanation;

    // Many to one
    private Infraction codeInfaction;
    private Jugement codeJugement;
    private Juridiction codeJuridiction;
    private Affaire numeroAffaire;
    private Personne numeroPers;

    // -- [id] ------------------------

    @Override
    @Column(name = "num_condamnation", precision = 19)
    @GeneratedValue
    @Id
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public Condamnation id(Long id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [peine] ------------------------

    @Size(max = 10)
    @Column(name = "peine", length = 10)
    public String getPeine() {
        return peine;
    }

    public void setPeine(String peine) {
        this.peine = peine;
    }

    public Condamnation peine(String peine) {
        setPeine(peine);
        return this;
    }

    // -- [montantAmende] ------------------------

    @Column(name = "montant_amende", precision = 2147483647)
    public Double getMontantAmende() {
        return montantAmende;
    }

    public void setMontantAmende(Double montantAmende) {
        this.montantAmende = montantAmende;
    }

    public Condamnation montantAmende(Double montantAmende) {
        setMontantAmende(montantAmende);
        return this;
    }

    // -- [dateCondamanation] ------------------------

    @Column(name = "date_condamanation", length = 13)
    @Temporal(DATE)
    public Date getDateCondamanation() {
        return dateCondamanation;
    }

    public void setDateCondamanation(Date dateCondamanation) {
        this.dateCondamanation = dateCondamanation;
    }

    public Condamnation dateCondamanation(Date dateCondamanation) {
        setDateCondamanation(dateCondamanation);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Condamnation.codeInfaction ==> Infraction.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "code_infaction", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public Infraction getCodeInfaction() {
        return codeInfaction;
    }

    /**
     * Set the {@link #codeInfaction} without adding this Condamnation instance on the passed {@link #codeInfaction}
     */
    public void setCodeInfaction(Infraction codeInfaction) {
        this.codeInfaction = codeInfaction;
    }

    public Condamnation codeInfaction(Infraction codeInfaction) {
        setCodeInfaction(codeInfaction);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Condamnation.codeJugement ==> Jugement.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "code_jugement", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public Jugement getCodeJugement() {
        return codeJugement;
    }

    /**
     * Set the {@link #codeJugement} without adding this Condamnation instance on the passed {@link #codeJugement}
     */
    public void setCodeJugement(Jugement codeJugement) {
        this.codeJugement = codeJugement;
    }

    public Condamnation codeJugement(Jugement codeJugement) {
        setCodeJugement(codeJugement);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Condamnation.codeJuridiction ==> Juridiction.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "code_juridiction", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public Juridiction getCodeJuridiction() {
        return codeJuridiction;
    }

    /**
     * Set the {@link #codeJuridiction} without adding this Condamnation instance on the passed {@link #codeJuridiction}
     */
    public void setCodeJuridiction(Juridiction codeJuridiction) {
        this.codeJuridiction = codeJuridiction;
    }

    public Condamnation codeJuridiction(Juridiction codeJuridiction) {
        setCodeJuridiction(codeJuridiction);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Condamnation.numeroAffaire ==> Affaire.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "numero_affaire")
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public Affaire getNumeroAffaire() {
        return numeroAffaire;
    }

    /**
     * Set the {@link #numeroAffaire} without adding this Condamnation instance on the passed {@link #numeroAffaire}
     */
    public void setNumeroAffaire(Affaire numeroAffaire) {
        this.numeroAffaire = numeroAffaire;
    }

    public Condamnation numeroAffaire(Affaire numeroAffaire) {
        setNumeroAffaire(numeroAffaire);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Condamnation.numeroPers ==> Personne.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "numero_pers", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public Personne getNumeroPers() {
        return numeroPers;
    }

    /**
     * Set the {@link #numeroPers} without adding this Condamnation instance on the passed {@link #numeroPers}
     */
    public void setNumeroPers(Personne numeroPers) {
        this.numeroPers = numeroPers;
    }

    public Condamnation numeroPers(Personne numeroPers) {
        setNumeroPers(numeroPers);
        return this;
    }

    /**
     * Apply the default values.
     */
    public Condamnation withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Condamnation && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Condamnation instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add(Condamnation_.id.getName(), getId()) //
                .add(Condamnation_.peine.getName(), getPeine()) //
                .add(Condamnation_.montantAmende.getName(), getMontantAmende()) //
                .add(Condamnation_.dateCondamanation.getName(), getDateCondamanation()) //
                .toString();
    }
}