/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 */
package com.artidev.oeildelynx.domain;

import java.util.Date;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Cpc.class)
public abstract class Cpc_ {

    // Raw attributes
    public static volatile SingularAttribute<Cpc, Integer> id;
    public static volatile SingularAttribute<Cpc, Double> montantCpc;
    public static volatile SingularAttribute<Cpc, Date> dateCpc;

    // Many to one
    public static volatile SingularAttribute<Cpc, Condamnation> numCondamnation;
}