/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/Entity.e.vm.java
 */
package com.artidev.oeildelynx.domain;

import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;
import static javax.persistence.TemporalType.DATE;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.validator.constraints.NotEmpty;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.Objects;

@Entity
@Table(name = "decouverte")
public class Decouverte implements Identifiable<String>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(Decouverte.class);

    // Raw attributes
    private String id;
    private Date dateDecouverte;
    private String observations;

    // Many to one
    private Unite codeUnite;
    private Recherche numeroRecherche;

    // -- [id] ------------------------

    @Override
    @Size(max = 10)
    @NotEmpty
    @Column(name = "numero_decouverte", length = 10)
    @Id
    public String getId() {
        return id;
    }

    @Override
    public void setId(String id) {
        this.id = id;
    }

    public Decouverte id(String id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null && !id.isEmpty();
    }

    // -- [dateDecouverte] ------------------------

    @Column(name = "date_decouverte", length = 13)
    @Temporal(DATE)
    public Date getDateDecouverte() {
        return dateDecouverte;
    }

    public void setDateDecouverte(Date dateDecouverte) {
        this.dateDecouverte = dateDecouverte;
    }

    public Decouverte dateDecouverte(Date dateDecouverte) {
        setDateDecouverte(dateDecouverte);
        return this;
    }

    // -- [observations] ------------------------

    @Size(max = 100)
    @Column(name = "observations", length = 100)
    public String getObservations() {
        return observations;
    }

    public void setObservations(String observations) {
        this.observations = observations;
    }

    public Decouverte observations(String observations) {
        setObservations(observations);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Decouverte.codeUnite ==> Unite.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "code_unite", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public Unite getCodeUnite() {
        return codeUnite;
    }

    /**
     * Set the {@link #codeUnite} without adding this Decouverte instance on the passed {@link #codeUnite}
     */
    public void setCodeUnite(Unite codeUnite) {
        this.codeUnite = codeUnite;
    }

    public Decouverte codeUnite(Unite codeUnite) {
        setCodeUnite(codeUnite);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Decouverte.numeroRecherche ==> Recherche.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "numero_recherche", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public Recherche getNumeroRecherche() {
        return numeroRecherche;
    }

    /**
     * Set the {@link #numeroRecherche} without adding this Decouverte instance on the passed {@link #numeroRecherche}
     */
    public void setNumeroRecherche(Recherche numeroRecherche) {
        this.numeroRecherche = numeroRecherche;
    }

    public Decouverte numeroRecherche(Recherche numeroRecherche) {
        setNumeroRecherche(numeroRecherche);
        return this;
    }

    /**
     * Apply the default values.
     */
    public Decouverte withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Decouverte && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Decouverte instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add(Decouverte_.id.getName(), getId()) //
                .add(Decouverte_.dateDecouverte.getName(), getDateDecouverte()) //
                .add(Decouverte_.observations.getName(), getObservations()) //
                .toString();
    }
}