/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/Entity.e.vm.java
 */
package com.artidev.oeildelynx.domain;

import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.Objects;

@Entity
@Table(name = "decouverte_de_personne", uniqueConstraints = {
        @UniqueConstraint(name = "pk_decouverte_de_personne", columnNames = { "numero_decouverte", "numero_pers" }),
        @UniqueConstraint(name = "pers_decouverte_pk", columnNames = { "numero_decouverte", "numero_pers" }) })
public class DecouverteDePersonne implements Identifiable<DecouverteDePersonnePk>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(DecouverteDePersonne.class);

    // Composite primary key
    private DecouverteDePersonnePk id = new DecouverteDePersonnePk();

    // Raw attributes
    private String etat;

    // Many to one
    private Decouverte numeroDecouverte;
    private Personne numeroPers;

    // -----------------------
    // Composite Primary Key
    // -----------------------

    /**
     * Returns the composite primary key.
     */
    @Override
    @EmbeddedId
    public DecouverteDePersonnePk getId() {
        return id;
    }

    /**
     * Set the composite primary key.
     * @param id the composite primary key.
     */
    @Override
    public void setId(DecouverteDePersonnePk id) {
        this.id = id;
    }

    public DecouverteDePersonne id(DecouverteDePersonnePk id) {
        setId(id);
        return this;
    }

    /**
     * Tells whether or not this instance has a non empty composite primary key set.
     * @return true if a non empty primary key is set, false otherwise
     */
    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return getId() != null && getId().areFieldsSet();
    }

    // -- [etat] ------------------------

    @Size(max = 10)
    @Column(name = "etat", length = 10)
    public String getEtat() {
        return etat;
    }

    public void setEtat(String etat) {
        this.etat = etat;
    }

    public DecouverteDePersonne etat(String etat) {
        setEtat(etat);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: DecouverteDePersonne.numeroDecouverte ==> Decouverte.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "numero_decouverte", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    @MapsId(value = "numeroDecouverte")
    public Decouverte getNumeroDecouverte() {
        return numeroDecouverte;
    }

    /**
     * Set the {@link #numeroDecouverte} without adding this DecouverteDePersonne instance on the passed {@link #numeroDecouverte}
     */
    public void setNumeroDecouverte(Decouverte numeroDecouverte) {
        this.numeroDecouverte = numeroDecouverte;
    }

    public DecouverteDePersonne numeroDecouverte(Decouverte numeroDecouverte) {
        setNumeroDecouverte(numeroDecouverte);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: DecouverteDePersonne.numeroPers ==> Personne.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "numero_pers", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    @MapsId(value = "numeroPers")
    public Personne getNumeroPers() {
        return numeroPers;
    }

    /**
     * Set the {@link #numeroPers} without adding this DecouverteDePersonne instance on the passed {@link #numeroPers}
     */
    public void setNumeroPers(Personne numeroPers) {
        this.numeroPers = numeroPers;
    }

    public DecouverteDePersonne numeroPers(Personne numeroPers) {
        setNumeroPers(numeroPers);
        return this;
    }

    /**
     * Apply the default values.
     */
    public DecouverteDePersonne withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof DecouverteDePersonne && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this DecouverteDePersonne instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add(DecouverteDePersonne_.etat.getName(), getEtat()) //
                .toString();
    }
}