/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/Entity.e.vm.java
 */
package com.artidev.oeildelynx.domain;

import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;
import static javax.persistence.TemporalType.DATE;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.Objects;

@Entity
@Table(name = "disparition")
public class Disparition implements Identifiable<Long>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(Disparition.class);

    // Raw attributes
    private Long id;
    private Date dateDisparition;
    private String conditionDisparition;

    // Many to one
    private Personne numeroPers;

    // -- [id] ------------------------

    @Override
    @Column(name = "numero_disparition", precision = 19)
    @GeneratedValue
    @Id
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public Disparition id(Long id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [dateDisparition] ------------------------

    @Column(name = "date_disparition", length = 13)
    @Temporal(DATE)
    public Date getDateDisparition() {
        return dateDisparition;
    }

    public void setDateDisparition(Date dateDisparition) {
        this.dateDisparition = dateDisparition;
    }

    public Disparition dateDisparition(Date dateDisparition) {
        setDateDisparition(dateDisparition);
        return this;
    }

    // -- [conditionDisparition] ------------------------

    @Size(max = 50)
    @Column(name = "condition_disparition", length = 50)
    public String getConditionDisparition() {
        return conditionDisparition;
    }

    public void setConditionDisparition(String conditionDisparition) {
        this.conditionDisparition = conditionDisparition;
    }

    public Disparition conditionDisparition(String conditionDisparition) {
        setConditionDisparition(conditionDisparition);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Disparition.numeroPers ==> Personne.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "numero_pers", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public Personne getNumeroPers() {
        return numeroPers;
    }

    /**
     * Set the {@link #numeroPers} without adding this Disparition instance on the passed {@link #numeroPers}
     */
    public void setNumeroPers(Personne numeroPers) {
        this.numeroPers = numeroPers;
    }

    public Disparition numeroPers(Personne numeroPers) {
        setNumeroPers(numeroPers);
        return this;
    }

    /**
     * Apply the default values.
     */
    public Disparition withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Disparition && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Disparition instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add(Disparition_.id.getName(), getId()) //
                .add(Disparition_.dateDisparition.getName(), getDateDisparition()) //
                .add(Disparition_.conditionDisparition.getName(), getConditionDisparition()) //
                .toString();
    }
}