/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/Entity.e.vm.java
 */
package com.artidev.oeildelynx.domain;

import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.Objects;

@Entity
@Table(name = "etab_penitencier")
public class EtabPenitencier implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(EtabPenitencier.class);

    // Raw attributes
    private Integer id;
    private String nomPenitencier;

    // Many to one
    private Localite codeLocalite;

    // -- [id] ------------------------

    @Override
    @Column(name = "code_penitencier", precision = 5)
    @GeneratedValue
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public EtabPenitencier id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [nomPenitencier] ------------------------

    @Size(max = 40)
    @Column(name = "nom_penitencier", length = 40)
    public String getNomPenitencier() {
        return nomPenitencier;
    }

    public void setNomPenitencier(String nomPenitencier) {
        this.nomPenitencier = nomPenitencier;
    }

    public EtabPenitencier nomPenitencier(String nomPenitencier) {
        setNomPenitencier(nomPenitencier);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: EtabPenitencier.codeLocalite ==> Localite.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "code_localite", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public Localite getCodeLocalite() {
        return codeLocalite;
    }

    /**
     * Set the {@link #codeLocalite} without adding this EtabPenitencier instance on the passed {@link #codeLocalite}
     */
    public void setCodeLocalite(Localite codeLocalite) {
        this.codeLocalite = codeLocalite;
    }

    public EtabPenitencier codeLocalite(Localite codeLocalite) {
        setCodeLocalite(codeLocalite);
        return this;
    }

    /**
     * Apply the default values.
     */
    public EtabPenitencier withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof EtabPenitencier && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this EtabPenitencier instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add(EtabPenitencier_.id.getName(), getId()) //
                .add(EtabPenitencier_.nomPenitencier.getName(), getNomPenitencier()) //
                .toString();
    }
}