/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/CompositePk.cpk.vm.java
 */
package com.artidev.oeildelynx.domain;

//import static org.apache.commons.lang.StringUtils.isNotEmpty;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Transient;

import com.google.common.base.Objects;

@Embeddable
public class ImplicationsPk implements Comparable<ImplicationsPk>, Serializable {
    private static final long serialVersionUID = 1L;

    private Integer numeroPers;
    private Integer codeUnite;
    private Integer numeroAffaire;

    public ImplicationsPk() {
    }

    public ImplicationsPk(Integer numeroPers, Integer codeUnite, Integer numeroAffaire) {
        this.numeroPers = numeroPers;
        this.codeUnite = codeUnite;
        this.numeroAffaire = numeroAffaire;
    }

    /**
     * Helper to determine if this composite primary key is fully set.
     */
    @Transient
    public boolean areFieldsSet() {
        return isNumeroPersSet() && isCodeUniteSet() && isNumeroAffaireSet();
    }

    /**
     * Helper method to determine if this instance is considered empty, that is,
     * if all the non primary key columns are null.
     */
    @Transient
    public boolean isEmpty() {
        return !isNumeroPersSet() && !isCodeUniteSet() && !isNumeroAffaireSet();
    }

    //-- [numeroPers] ------------------------------

    @Column(name = "numero_pers", nullable = false, precision = 10)
    public Integer getNumeroPers() {
        return numeroPers;
    }

    public void setNumeroPers(Integer numeroPers) {
        this.numeroPers = numeroPers;
    }

    public ImplicationsPk numeroPers(Integer numeroPers) {
        setNumeroPers(numeroPers);
        return this;
    }

    /**
     * Helper that determines if this attribute is set or not.
     */
    @Transient
    public boolean isNumeroPersSet() {
        return getNumeroPers() != null;
    }

    //-- [codeUnite] ------------------------------

    @Column(name = "code_unite", nullable = false, precision = 10)
    public Integer getCodeUnite() {
        return codeUnite;
    }

    public void setCodeUnite(Integer codeUnite) {
        this.codeUnite = codeUnite;
    }

    public ImplicationsPk codeUnite(Integer codeUnite) {
        setCodeUnite(codeUnite);
        return this;
    }

    /**
     * Helper that determines if this attribute is set or not.
     */
    @Transient
    public boolean isCodeUniteSet() {
        return getCodeUnite() != null;
    }

    //-- [numeroAffaire] ------------------------------

    @Column(name = "numero_affaire", nullable = false, precision = 10)
    public Integer getNumeroAffaire() {
        return numeroAffaire;
    }

    public void setNumeroAffaire(Integer numeroAffaire) {
        this.numeroAffaire = numeroAffaire;
    }

    public ImplicationsPk numeroAffaire(Integer numeroAffaire) {
        setNumeroAffaire(numeroAffaire);
        return this;
    }

    /**
     * Helper that determines if this attribute is set or not.
     */
    @Transient
    public boolean isNumeroAffaireSet() {
        return getNumeroAffaire() != null;
    }

    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof ImplicationsPk && hashCode() == other.hashCode());
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(getNumeroPers(), getCodeUnite(), getNumeroAffaire());
    }

    @Override
    public int compareTo(ImplicationsPk other) {
        return other == null ? -1 : hashCode() - other.hashCode();
    }

    /**
     * Return the string representation of the composite primary key, it should be reversable by version produced by the {@link #String()} method
     */
    @Override
    public String toString() {
        StringBuilder result = new StringBuilder();
        if (isNumeroPersSet()) {
            result.append(getNumeroPers());
        }
        result.append(":");
        if (isCodeUniteSet()) {
            result.append(getCodeUnite());
        }
        result.append(":");
        if (isNumeroAffaireSet()) {
            result.append(getNumeroAffaire());
        }

        return result.toString();
    }

    /**
     * Build an instance from a string version produced by the {@link #toString()} method
     */
    /*public static ImplicationsPk fromString(String string) {
        ImplicationsPk result = new ImplicationsPk();
        String[] values = string.split(":");
        if (isNotEmpty(values[0])) {
            result.setNumeroPers(Integer.valueOf(values[0]));
        }
        if (isNotEmpty(values[1])) {
            result.setCodeUnite(Integer.valueOf(values[1]));
        }
        if (isNotEmpty(values[2])) {
            result.setNumeroAffaire(Integer.valueOf(values[2]));
        }

        return result;
    }*/
}
