/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/CompositePk_.cpk.vm.java
 */
package com.artidev.oeildelynx.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(ImplicationsPk.class)
public abstract class ImplicationsPk_ {
    // pk attributes
    public static volatile SingularAttribute<ImplicationsPk, Integer> numeroPers;
    public static volatile SingularAttribute<ImplicationsPk, Integer> codeUnite;
    public static volatile SingularAttribute<ImplicationsPk, Integer> numeroAffaire;
}
