/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/Entity.e.vm.java
 */
package com.artidev.oeildelynx.domain;

import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlTransient;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.Objects;

@Entity
@Table(name = "indice")
public class Indice implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(Indice.class);

    // Raw attributes
    private Integer id;
    private Integer codeIndice;
    private String imageIndice;

    // Many to one
    private Affaire numeroAffaire;

    // -- [id] ------------------------

    @Override
    @Column(name = "numero_indice", precision = 10)
    @GeneratedValue
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public Indice id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [codeIndice] ------------------------

    @Column(name = "code_indice", precision = 10)
    public Integer getCodeIndice() {
        return codeIndice;
    }

    public void setCodeIndice(Integer codeIndice) {
        this.codeIndice = codeIndice;
    }

    public Indice codeIndice(Integer codeIndice) {
        setCodeIndice(codeIndice);
        return this;
    }

    // -- [imageIndice] ------------------------

    //@FixedLength(length = 254)
    @Column(name = "image_indice", length = 254)
    public String getImageIndice() {
        return imageIndice;
    }

    public void setImageIndice(String imageIndice) {
        this.imageIndice = imageIndice;
    }

    public Indice imageIndice(String imageIndice) {
        setImageIndice(imageIndice);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Indice.numeroAffaire ==> Affaire.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "numero_affaire", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public Affaire getNumeroAffaire() {
        return numeroAffaire;
    }

    /**
     * Set the {@link #numeroAffaire} without adding this Indice instance on the passed {@link #numeroAffaire}
     */
    public void setNumeroAffaire(Affaire numeroAffaire) {
        this.numeroAffaire = numeroAffaire;
    }

    public Indice numeroAffaire(Affaire numeroAffaire) {
        setNumeroAffaire(numeroAffaire);
        return this;
    }

    /**
     * Apply the default values.
     */
    public Indice withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Indice && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Indice instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add(Indice_.id.getName(), getId()) //
                .add(Indice_.codeIndice.getName(), getCodeIndice()) //
                .add(Indice_.imageIndice.getName(), getImageIndice()) //
                .toString();
    }
}