/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/Entity.e.vm.java
 */
package com.artidev.oeildelynx.domain;

import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.Objects;

@Entity
@Table(name = "infraction")
public class Infraction implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(Infraction.class);

    // Raw attributes
    private Integer id;
    private String libelleInfractio;

    // Many to one
    private FamilleInfraction codeCatgorie;

    // -- [id] ------------------------

    @Override
    @Column(name = "code_infaction", precision = 10)
    @GeneratedValue
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public Infraction id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [libelleInfractio] ------------------------

    @Size(max = 100)
    @Column(name = "libelle_infractio", length = 100)
    public String getLibelleInfractio() {
        return libelleInfractio;
    }

    public void setLibelleInfractio(String libelleInfractio) {
        this.libelleInfractio = libelleInfractio;
    }

    public Infraction libelleInfractio(String libelleInfractio) {
        setLibelleInfractio(libelleInfractio);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Infraction.codeCatgorie ==> FamilleInfraction.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "code_catgorie", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public FamilleInfraction getCodeCatgorie() {
        return codeCatgorie;
    }

    /**
     * Set the {@link #codeCatgorie} without adding this Infraction instance on the passed {@link #codeCatgorie}
     */
    public void setCodeCatgorie(FamilleInfraction codeCatgorie) {
        this.codeCatgorie = codeCatgorie;
    }

    public Infraction codeCatgorie(FamilleInfraction codeCatgorie) {
        setCodeCatgorie(codeCatgorie);
        return this;
    }

    /**
     * Apply the default values.
     */
    public Infraction withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Infraction && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Infraction instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add(Infraction_.id.getName(), getId()) //
                .add(Infraction_.libelleInfractio.getName(), getLibelleInfractio()) //
                .toString();
    }
}