/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/Entity.e.vm.java
 */
package com.artidev.oeildelynx.domain;

import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;
import static javax.persistence.TemporalType.DATE;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlTransient;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.Objects;

@Entity
@Table(name = "interpellation")
public class Interpellation implements Identifiable<Long>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(Interpellation.class);

    // Raw attributes
    private Long id;
    private Date dateDebutInterp;
    private Date dateFinInterp;
    private Boolean deferer;

    // Many to one
    private Unite codeUnite;
    private Personne numeroPers;
    private Affaire numeroAffaire;

    // -- [id] ------------------------

    @Override
    @Column(name = "numero_interp", precision = 19)
    @GeneratedValue
    @Id
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public Interpellation id(Long id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [dateDebutInterp] ------------------------

    @Column(name = "date_debut_interp", length = 13)
    @Temporal(DATE)
    public Date getDateDebutInterp() {
        return dateDebutInterp;
    }

    public void setDateDebutInterp(Date dateDebutInterp) {
        this.dateDebutInterp = dateDebutInterp;
    }

    public Interpellation dateDebutInterp(Date dateDebutInterp) {
        setDateDebutInterp(dateDebutInterp);
        return this;
    }

    // -- [dateFinInterp] ------------------------

    @Column(name = "date_fin_interp", length = 13)
    @Temporal(DATE)
    public Date getDateFinInterp() {
        return dateFinInterp;
    }

    public void setDateFinInterp(Date dateFinInterp) {
        this.dateFinInterp = dateFinInterp;
    }

    public Interpellation dateFinInterp(Date dateFinInterp) {
        setDateFinInterp(dateFinInterp);
        return this;
    }

    // -- [deferer] ------------------------

    @Column(name = "deferer", length = 1)
    public Boolean getDeferer() {
        return deferer;
    }

    public void setDeferer(Boolean deferer) {
        this.deferer = deferer;
    }

    public Interpellation deferer(Boolean deferer) {
        setDeferer(deferer);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Interpellation.codeUnite ==> Unite.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "code_unite", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public Unite getCodeUnite() {
        return codeUnite;
    }

    /**
     * Set the {@link #codeUnite} without adding this Interpellation instance on the passed {@link #codeUnite}
     */
    public void setCodeUnite(Unite codeUnite) {
        this.codeUnite = codeUnite;
    }

    public Interpellation codeUnite(Unite codeUnite) {
        setCodeUnite(codeUnite);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Interpellation.numeroPers ==> Personne.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "numero_pers", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public Personne getNumeroPers() {
        return numeroPers;
    }

    /**
     * Set the {@link #numeroPers} without adding this Interpellation instance on the passed {@link #numeroPers}
     */
    public void setNumeroPers(Personne numeroPers) {
        this.numeroPers = numeroPers;
    }

    public Interpellation numeroPers(Personne numeroPers) {
        setNumeroPers(numeroPers);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Interpellation.numeroAffaire ==> Affaire.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "numero_affaire", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public Affaire getNumeroAffaire() {
        return numeroAffaire;
    }

    /**
     * Set the {@link #numeroAffaire} without adding this Interpellation instance on the passed {@link #numeroAffaire}
     */
    public void setNumeroAffaire(Affaire numeroAffaire) {
        this.numeroAffaire = numeroAffaire;
    }

    public Interpellation numeroAffaire(Affaire numeroAffaire) {
        setNumeroAffaire(numeroAffaire);
        return this;
    }

    /**
     * Apply the default values.
     */
    public Interpellation withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Interpellation && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Interpellation instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add(Interpellation_.id.getName(), getId()) //
                .add(Interpellation_.dateDebutInterp.getName(), getDateDebutInterp()) //
                .add(Interpellation_.dateFinInterp.getName(), getDateFinInterp()) //
                .add(Interpellation_.deferer.getName(), getDeferer()) //
                .toString();
    }
}