/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/Entity.e.vm.java
 */
package com.artidev.oeildelynx.domain;

import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;
import static javax.persistence.TemporalType.DATE;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlTransient;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.Objects;

@Entity
@Table(name = "liste_detenus", uniqueConstraints = {
        @UniqueConstraint(name = "pk_liste_detenus", columnNames = { "numero_pers", "code_penitencier", "numero_mandat" }),
        @UniqueConstraint(name = "association_25_pk", columnNames = { "numero_pers", "code_penitencier", "numero_mandat" }) })
public class ListeDetenus implements Identifiable<ListeDetenusPk>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(ListeDetenus.class);

    // Composite primary key
    private ListeDetenusPk id = new ListeDetenusPk();

    // Raw attributes
    private Date dateDebut_;
    private Date dateFinDetention;

    // Many to one
    private Mandat numeroMandat;
    private EtabPenitencier codePenitencier;
    private Personne numeroPers;

    // -----------------------
    // Composite Primary Key
    // -----------------------

    /**
     * Returns the composite primary key.
     */
    @Override
    @EmbeddedId
    public ListeDetenusPk getId() {
        return id;
    }

    /**
     * Set the composite primary key.
     * @param id the composite primary key.
     */
    @Override
    public void setId(ListeDetenusPk id) {
        this.id = id;
    }

    public ListeDetenus id(ListeDetenusPk id) {
        setId(id);
        return this;
    }

    /**
     * Tells whether or not this instance has a non empty composite primary key set.
     * @return true if a non empty primary key is set, false otherwise
     */
    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return getId() != null && getId().areFieldsSet();
    }

    // -- [dateDebut_] ------------------------

    @Column(name = "date_debut_", length = 13)
    @Temporal(DATE)
    public Date getDateDebut_() {
        return dateDebut_;
    }

    public void setDateDebut_(Date dateDebut_) {
        this.dateDebut_ = dateDebut_;
    }

    public ListeDetenus dateDebut_(Date dateDebut_) {
        setDateDebut_(dateDebut_);
        return this;
    }

    // -- [dateFinDetention] ------------------------

    @Column(name = "date_fin_detention", length = 13)
    @Temporal(DATE)
    public Date getDateFinDetention() {
        return dateFinDetention;
    }

    public void setDateFinDetention(Date dateFinDetention) {
        this.dateFinDetention = dateFinDetention;
    }

    public ListeDetenus dateFinDetention(Date dateFinDetention) {
        setDateFinDetention(dateFinDetention);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: ListeDetenus.numeroMandat ==> Mandat.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "numero_mandat", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    @MapsId(value = "numeroMandat")
    public Mandat getNumeroMandat() {
        return numeroMandat;
    }

    /**
     * Set the {@link #numeroMandat} without adding this ListeDetenus instance on the passed {@link #numeroMandat}
     */
    public void setNumeroMandat(Mandat numeroMandat) {
        this.numeroMandat = numeroMandat;
    }

    public ListeDetenus numeroMandat(Mandat numeroMandat) {
        setNumeroMandat(numeroMandat);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: ListeDetenus.codePenitencier ==> EtabPenitencier.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "code_penitencier", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    @MapsId(value = "codePenitencier")
    public EtabPenitencier getCodePenitencier() {
        return codePenitencier;
    }

    /**
     * Set the {@link #codePenitencier} without adding this ListeDetenus instance on the passed {@link #codePenitencier}
     */
    public void setCodePenitencier(EtabPenitencier codePenitencier) {
        this.codePenitencier = codePenitencier;
    }

    public ListeDetenus codePenitencier(EtabPenitencier codePenitencier) {
        setCodePenitencier(codePenitencier);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: ListeDetenus.numeroPers ==> Personne.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "numero_pers", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    @MapsId(value = "numeroPers")
    public Personne getNumeroPers() {
        return numeroPers;
    }

    /**
     * Set the {@link #numeroPers} without adding this ListeDetenus instance on the passed {@link #numeroPers}
     */
    public void setNumeroPers(Personne numeroPers) {
        this.numeroPers = numeroPers;
    }

    public ListeDetenus numeroPers(Personne numeroPers) {
        setNumeroPers(numeroPers);
        return this;
    }

    /**
     * Apply the default values.
     */
    public ListeDetenus withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof ListeDetenus && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this ListeDetenus instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add(ListeDetenus_.dateDebut_.getName(), getDateDebut_()) //
                .add(ListeDetenus_.dateFinDetention.getName(), getDateFinDetention()) //
                .toString();
    }
}