/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/CompositePk.cpk.vm.java
 */
package com.artidev.oeildelynx.domain;

//import static org.apache.commons.lang.StringUtils.isNotEmpty;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Transient;

import com.google.common.base.Objects;

@Embeddable
public class ListeDetenusPk implements Comparable<ListeDetenusPk>, Serializable {
    private static final long serialVersionUID = 1L;

    private Integer numeroPers;
    private Integer codePenitencier;
    private String numeroMandat;

    public ListeDetenusPk() {
    }

    public ListeDetenusPk(Integer numeroPers, Integer codePenitencier, String numeroMandat) {
        this.numeroPers = numeroPers;
        this.codePenitencier = codePenitencier;
        this.numeroMandat = numeroMandat;
    }

    /**
     * Helper to determine if this composite primary key is fully set.
     */
    @Transient
    public boolean areFieldsSet() {
        return isNumeroPersSet() && isCodePenitencierSet() && isNumeroMandatSet();
    }

    /**
     * Helper method to determine if this instance is considered empty, that is,
     * if all the non primary key columns are null.
     */
    @Transient
    public boolean isEmpty() {
        return !isNumeroPersSet() && !isCodePenitencierSet() && !isNumeroMandatSet();
    }

    //-- [numeroPers] ------------------------------

    @Column(name = "numero_pers", nullable = false, precision = 10)
    public Integer getNumeroPers() {
        return numeroPers;
    }

    public void setNumeroPers(Integer numeroPers) {
        this.numeroPers = numeroPers;
    }

    public ListeDetenusPk numeroPers(Integer numeroPers) {
        setNumeroPers(numeroPers);
        return this;
    }

    /**
     * Helper that determines if this attribute is set or not.
     */
    @Transient
    public boolean isNumeroPersSet() {
        return getNumeroPers() != null;
    }

    //-- [codePenitencier] ------------------------------

    @Column(name = "code_penitencier", nullable = false, precision = 5)
    public Integer getCodePenitencier() {
        return codePenitencier;
    }

    public void setCodePenitencier(Integer codePenitencier) {
        this.codePenitencier = codePenitencier;
    }

    public ListeDetenusPk codePenitencier(Integer codePenitencier) {
        setCodePenitencier(codePenitencier);
        return this;
    }

    /**
     * Helper that determines if this attribute is set or not.
     */
    @Transient
    public boolean isCodePenitencierSet() {
        return getCodePenitencier() != null;
    }

    //-- [numeroMandat] ------------------------------

    @Column(name = "numero_mandat", nullable = false, length = 25)
    public String getNumeroMandat() {
        return numeroMandat;
    }

    public void setNumeroMandat(String numeroMandat) {
        this.numeroMandat = numeroMandat;
    }

    public ListeDetenusPk numeroMandat(String numeroMandat) {
        setNumeroMandat(numeroMandat);
        return this;
    }

    /**
     * Helper that determines if this attribute is set or not.
     */
    @Transient
    public boolean isNumeroMandatSet() {
        return getNumeroMandat() != null && !getNumeroMandat().isEmpty();
    }

    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof ListeDetenusPk && hashCode() == other.hashCode());
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(getNumeroPers(), getCodePenitencier(), getNumeroMandat());
    }

    @Override
    public int compareTo(ListeDetenusPk other) {
        return other == null ? -1 : hashCode() - other.hashCode();
    }

    /**
     * Return the string representation of the composite primary key, it should be reversable by version produced by the {@link #String()} method
     */
    @Override
    public String toString() {
        StringBuilder result = new StringBuilder();
        if (isNumeroPersSet()) {
            result.append(getNumeroPers());
        }
        result.append(":");
        if (isCodePenitencierSet()) {
            result.append(getCodePenitencier());
        }
        result.append(":");
        if (isNumeroMandatSet()) {
            result.append(getNumeroMandat());
        }

        return result.toString();
    }

    /**
     * Build an instance from a string version produced by the {@link #toString()} method
     */
    /*public static ListeDetenusPk fromString(String string) {
        ListeDetenusPk result = new ListeDetenusPk();
        String[] values = string.split(":");
        if (isNotEmpty(values[0])) {
            result.setNumeroPers(Integer.valueOf(values[0]));
        }
        if (isNotEmpty(values[1])) {
            result.setCodePenitencier(Integer.valueOf(values[1]));
        }
        if (isNotEmpty(values[2])) {
            result.setNumeroMandat(values[2]);
        }

        return result;
    }*/
}
