/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 */
package com.artidev.oeildelynx.domain;

import java.util.Date;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Mandat.class)
public abstract class Mandat_ {

    // Raw attributes
    public static volatile SingularAttribute<Mandat, String> id;
    public static volatile SingularAttribute<Mandat, Date> dateMandat;
    public static volatile SingularAttribute<Mandat, String> archiveMandat;

    // Many to one
    public static volatile SingularAttribute<Mandat, TypeMandant> codeTypeMandar;
    public static volatile SingularAttribute<Mandat, Condamnation> numCondamnation;
}