/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/Entity.e.vm.java
 */
package com.artidev.oeildelynx.domain;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.Objects;

@Entity
@Table(name = "pays")
public class Pays implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(Pays.class);

    // Raw attributes
    private Integer id;
    private String nomPays;
    private String citoyenete;

    // -- [id] ------------------------

    @Override
    @Column(name = "code_pays", precision = 10)
    @GeneratedValue
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public Pays id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [nomPays] ------------------------

    @Size(max = 30)
    @Column(name = "nom_pays", length = 30)
    public String getNomPays() {
        return nomPays;
    }

    public void setNomPays(String nomPays) {
        this.nomPays = nomPays;
    }

    public Pays nomPays(String nomPays) {
        setNomPays(nomPays);
        return this;
    }

    // -- [citoyenete] ------------------------

    @Size(max = 35)
    @Column(name = "citoyenete", length = 35)
    public String getCitoyenete() {
        return citoyenete;
    }

    public void setCitoyenete(String citoyenete) {
        this.citoyenete = citoyenete;
    }

    public Pays citoyenete(String citoyenete) {
        setCitoyenete(citoyenete);
        return this;
    }

    /**
     * Apply the default values.
     */
    public Pays withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Pays && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Pays instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add(Pays_.id.getName(), getId()) //
                .add(Pays_.nomPays.getName(), getNomPays()) //
                .add(Pays_.citoyenete.getName(), getCitoyenete()) //
                .toString();
    }
}