/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 */
package com.artidev.oeildelynx.domain;

import java.util.Date;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Personne.class)
public abstract class Personne_ {

    // Raw attributes
    public static volatile SingularAttribute<Personne, Integer> id;
    public static volatile SingularAttribute<Personne, String> nomPers;
    public static volatile SingularAttribute<Personne, String> prenomsPers;
    public static volatile SingularAttribute<Personne, Date> dateNaissancePersonne;
    public static volatile SingularAttribute<Personne, String> nomPrenomsPere;
    public static volatile SingularAttribute<Personne, String> nomPrenomsMere;

    // Many to one
    public static volatile SingularAttribute<Personne, Genre> codeGenre;
    public static volatile SingularAttribute<Personne, SitMatrimoniale> codeSituation;
    public static volatile SingularAttribute<Personne, Pays> codePays;
    public static volatile SingularAttribute<Personne, Religion> codeReligion;
    public static volatile SingularAttribute<Personne, Ethnie> codeEthnie;
    public static volatile SingularAttribute<Personne, Profession> codeProfession;
    public static volatile SingularAttribute<Personne, Localite> codeLocalite;
}