/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 */
package com.artidev.oeildelynx.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(ProfilBiometrique.class)
public abstract class ProfilBiometrique_ {
    // Composite primary key
    public static volatile SingularAttribute<ProfilBiometrique, ProfilBiometriquePk> id;

    // Raw attributes
    public static volatile SingularAttribute<ProfilBiometrique, Long> valeur;
    public static volatile SingularAttribute<ProfilBiometrique, String> imageProfile;

    // Many to one
    public static volatile SingularAttribute<ProfilBiometrique, Personne> numeroPers;
    public static volatile SingularAttribute<ProfilBiometrique, Biometrie> codeMarquage;
}