/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/Entity.e.vm.java
 */
package com.artidev.oeildelynx.domain;

import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;
import static javax.persistence.TemporalType.DATE;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.validator.constraints.NotEmpty;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.Objects;

@Entity
@Table(name = "pv")
public class Pv implements Identifiable<String>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(Pv.class);

    // Raw attributes
    private String id;
    private String analysePv;
    private Date datePv;
    private String archivePv;

    // Many to one
    private Unite codeUnite;
    private Affaire numeroAffaire;

    // -- [id] ------------------------

    @Override
    @Size(max = 10)
    @NotEmpty
    @Column(name = "numero_pv", length = 10)
    @Id
    public String getId() {
        return id;
    }

    @Override
    public void setId(String id) {
        this.id = id;
    }

    public Pv id(String id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null && !id.isEmpty();
    }

    // -- [analysePv] ------------------------

    @Size(max = 100)
    @Column(name = "analyse_pv", length = 100)
    public String getAnalysePv() {
        return analysePv;
    }

    public void setAnalysePv(String analysePv) {
        this.analysePv = analysePv;
    }

    public Pv analysePv(String analysePv) {
        setAnalysePv(analysePv);
        return this;
    }

    // -- [datePv] ------------------------

    @Column(name = "date_pv", length = 13)
    @Temporal(DATE)
    public Date getDatePv() {
        return datePv;
    }

    public void setDatePv(Date datePv) {
        this.datePv = datePv;
    }

    public Pv datePv(Date datePv) {
        setDatePv(datePv);
        return this;
    }

    // -- [archivePv] ------------------------

   // @FixedLength(length = 254)
    @Column(name = "archive_pv", length = 254)
    public String getArchivePv() {
        return archivePv;
    }

    public void setArchivePv(String archivePv) {
        this.archivePv = archivePv;
    }

    public Pv archivePv(String archivePv) {
        setArchivePv(archivePv);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Pv.codeUnite ==> Unite.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "code_unite", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public Unite getCodeUnite() {
        return codeUnite;
    }

    /**
     * Set the {@link #codeUnite} without adding this Pv instance on the passed {@link #codeUnite}
     */
    public void setCodeUnite(Unite codeUnite) {
        this.codeUnite = codeUnite;
    }

    public Pv codeUnite(Unite codeUnite) {
        setCodeUnite(codeUnite);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Pv.numeroAffaire ==> Affaire.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "numero_affaire", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public Affaire getNumeroAffaire() {
        return numeroAffaire;
    }

    /**
     * Set the {@link #numeroAffaire} without adding this Pv instance on the passed {@link #numeroAffaire}
     */
    public void setNumeroAffaire(Affaire numeroAffaire) {
        this.numeroAffaire = numeroAffaire;
    }

    public Pv numeroAffaire(Affaire numeroAffaire) {
        setNumeroAffaire(numeroAffaire);
        return this;
    }

    /**
     * Apply the default values.
     */
    public Pv withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Pv && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Pv instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add(Pv_.id.getName(), getId()) //
                .add(Pv_.analysePv.getName(), getAnalysePv()) //
                .add(Pv_.datePv.getName(), getDatePv()) //
                .add(Pv_.archivePv.getName(), getArchivePv()) //
                .toString();
    }
}