/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/Entity.e.vm.java
 */
package com.artidev.oeildelynx.domain;

import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;
import static javax.persistence.TemporalType.DATE;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.Objects;

@Entity
@Table(name = "recherche")
public class Recherche implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(Recherche.class);

    // Raw attributes
    private Integer id;
    private Date dateLancement;
    private String casDecouverte;

    // Many to one
    private Unite codeUnite;
    private Mandat numeroMandat;
    private Infraction codeInfaction;

    // Many to many
    private List<Personne> numeroPerss = new ArrayList<Personne>();

    // -- [id] ------------------------

    @Override
    @Column(name = "numero_recherche", precision = 10)
    @GeneratedValue
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public Recherche id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [dateLancement] ------------------------

    @Column(name = "date_lancement", length = 13)
    @Temporal(DATE)
    public Date getDateLancement() {
        return dateLancement;
    }

    public void setDateLancement(Date dateLancement) {
        this.dateLancement = dateLancement;
    }

    public Recherche dateLancement(Date dateLancement) {
        setDateLancement(dateLancement);
        return this;
    }

    // -- [casDecouverte] ------------------------

    @Size(max = 100)
    @Column(name = "cas_decouverte", length = 100)
    public String getCasDecouverte() {
        return casDecouverte;
    }

    public void setCasDecouverte(String casDecouverte) {
        this.casDecouverte = casDecouverte;
    }

    public Recherche casDecouverte(String casDecouverte) {
        setCasDecouverte(casDecouverte);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Recherche.codeUnite ==> Unite.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "code_unite")
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public Unite getCodeUnite() {
        return codeUnite;
    }

    /**
     * Set the {@link #codeUnite} without adding this Recherche instance on the passed {@link #codeUnite}
     */
    public void setCodeUnite(Unite codeUnite) {
        this.codeUnite = codeUnite;
    }

    public Recherche codeUnite(Unite codeUnite) {
        setCodeUnite(codeUnite);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Recherche.numeroMandat ==> Mandat.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "numero_mandat")
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public Mandat getNumeroMandat() {
        return numeroMandat;
    }

    /**
     * Set the {@link #numeroMandat} without adding this Recherche instance on the passed {@link #numeroMandat}
     */
    public void setNumeroMandat(Mandat numeroMandat) {
        this.numeroMandat = numeroMandat;
    }

    public Recherche numeroMandat(Mandat numeroMandat) {
        setNumeroMandat(numeroMandat);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Recherche.codeInfaction ==> Infraction.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "code_infaction")
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public Infraction getCodeInfaction() {
        return codeInfaction;
    }

    /**
     * Set the {@link #codeInfaction} without adding this Recherche instance on the passed {@link #codeInfaction}
     */
    public void setCodeInfaction(Infraction codeInfaction) {
        this.codeInfaction = codeInfaction;
    }

    public Recherche codeInfaction(Infraction codeInfaction) {
        setCodeInfaction(codeInfaction);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to Many
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
    // many-to-many: recherche ==> numeroPerss
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

    /**
     * Returns the {@link #numeroPerss} list.
     */
    @JoinTable(name = "personnes_recherchees", joinColumns = @JoinColumn(name = "numero_recherche"), inverseJoinColumns = @JoinColumn(name = "numero_pers"))
    @ManyToMany(cascade = { PERSIST, MERGE })
    public List<Personne> getNumeroPerss() {
        return numeroPerss;
    }

    /**
     * Set the {@link #numeroPerss} list.
     *
     * @param numeroPerss the list of Personne
     */
    public void setNumeroPerss(List<Personne> numeroPerss) {
        this.numeroPerss = numeroPerss;
    }

    /**
     * Helper method to add the passed {@link Personne} to the {@link #numeroPerss} list.
     */
    public boolean addNumeroPers(Personne numeroPers) {
        return getNumeroPerss().add(numeroPers);
    }

    /**
     * Helper method to remove the passed {@link Personne} from the {@link #numeroPerss} list.
     */
    public boolean removeNumeroPers(Personne numeroPers) {
        return getNumeroPerss().remove(numeroPers);
    }

    /**
     * Helper method to determine if the passed {@link Personne} is present in the {@link #numeroPerss} list.
     */
    public boolean containsNumeroPers(Personne numeroPers) {
        return getNumeroPerss() != null && getNumeroPerss().contains(numeroPers);
    }

    /**
     * Apply the default values.
     */
    public Recherche withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Recherche && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Recherche instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add(Recherche_.id.getName(), getId()) //
                .add(Recherche_.dateLancement.getName(), getDateLancement()) //
                .add(Recherche_.casDecouverte.getName(), getCasDecouverte()) //
                .toString();
    }
}