/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 */
package com.artidev.oeildelynx.domain;

import java.util.Date;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Recherche.class)
public abstract class Recherche_ {

    // Raw attributes
    public static volatile SingularAttribute<Recherche, Integer> id;
    public static volatile SingularAttribute<Recherche, Date> dateLancement;
    public static volatile SingularAttribute<Recherche, String> casDecouverte;

    // Many to one
    public static volatile SingularAttribute<Recherche, Unite> codeUnite;
    public static volatile SingularAttribute<Recherche, Mandat> numeroMandat;
    public static volatile SingularAttribute<Recherche, Infraction> codeInfaction;

    // Many to many
    public static volatile ListAttribute<Recherche, Personne> numeroPerss;
}