/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 */
package com.artidev.oeildelynx.domain;

import java.util.Date;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(ResidencePersonne.class)
public abstract class ResidencePersonne_ {
    // Composite primary key
    public static volatile SingularAttribute<ResidencePersonne, ResidencePersonnePk> id;

    // Many to one
    public static volatile SingularAttribute<ResidencePersonne, Personne> numeroPers;
    public static volatile SingularAttribute<ResidencePersonne, Localite> codeLocalite;
    public static volatile SingularAttribute<ResidencePersonne, Date> date;
}