/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/CompositePk_.cpk.vm.java
 */
package com.artidev.oeildelynx.domain;

import java.util.Date;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(ResidencePersonnePk.class)
public abstract class ResidencePersonnePk_ {
    // pk attributes
    public static volatile SingularAttribute<ResidencePersonnePk, Integer> numeroPers;
    public static volatile SingularAttribute<ResidencePersonnePk, Integer> codeLocalite;
    public static volatile SingularAttribute<ResidencePersonnePk, Date> date;
}
