/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/Entity.e.vm.java
 */
package com.artidev.oeildelynx.domain;

import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.validator.constraints.NotEmpty;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.Objects;

@Entity
@Table(name = "vehicule")
public class Vehicule implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(Vehicule.class);

    // Raw attributes
    private Integer id;
    private String designationBien;
    private String immatriculation;
    private String numeroChassis;

    // Many to one
    private Modele codeModele;
    private Type codeType;
    private Couleur codeCouleur;

    // One to one
    private Biens biens;

    // -- [id] ------------------------

    @Override
    @Column(name = "numero_bien", precision = 10)
    @GeneratedValue
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public Vehicule id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [designationBien] ------------------------

    @Size(max = 30)
    @Column(name = "designation_bien", length = 30)
    public String getDesignationBien() {
        return designationBien;
    }

    public void setDesignationBien(String designationBien) {
        this.designationBien = designationBien;
    }

    public Vehicule designationBien(String designationBien) {
        setDesignationBien(designationBien);
        return this;
    }

    // -- [immatriculation] ------------------------

    @Size(max = 10)
    @NotEmpty
    @Column(name = "immatriculation", nullable = false, length = 10)
    public String getImmatriculation() {
        return immatriculation;
    }

    public void setImmatriculation(String immatriculation) {
        this.immatriculation = immatriculation;
    }

    public Vehicule immatriculation(String immatriculation) {
        setImmatriculation(immatriculation);
        return this;
    }

    // -- [numeroChassis] ------------------------

    @Size(max = 10)
    @Column(name = "numero_chassis", length = 10)
    public String getNumeroChassis() {
        return numeroChassis;
    }

    public void setNumeroChassis(String numeroChassis) {
        this.numeroChassis = numeroChassis;
    }

    public Vehicule numeroChassis(String numeroChassis) {
        setNumeroChassis(numeroChassis);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Vehicule.codeModele ==> Modele.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "code_modele", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public Modele getCodeModele() {
        return codeModele;
    }

    /**
     * Set the {@link #codeModele} without adding this Vehicule instance on the passed {@link #codeModele}
     */
    public void setCodeModele(Modele codeModele) {
        this.codeModele = codeModele;
    }

    public Vehicule codeModele(Modele codeModele) {
        setCodeModele(codeModele);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Vehicule.codeType ==> Type.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "code_type", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public Type getCodeType() {
        return codeType;
    }

    /**
     * Set the {@link #codeType} without adding this Vehicule instance on the passed {@link #codeType}
     */
    public void setCodeType(Type codeType) {
        this.codeType = codeType;
    }

    public Vehicule codeType(Type codeType) {
        setCodeType(codeType);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Vehicule.codeCouleur ==> Couleur.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "code_couleur", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public Couleur getCodeCouleur() {
        return codeCouleur;
    }

    /**
     * Set the {@link #codeCouleur} without adding this Vehicule instance on the passed {@link #codeCouleur}
     */
    public void setCodeCouleur(Couleur codeCouleur) {
        this.codeCouleur = codeCouleur;
    }

    public Vehicule codeCouleur(Couleur codeCouleur) {
        setCodeCouleur(codeCouleur);
        return this;
    }

    // -----------------------------------------------------------------
    // One to one
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // Owner side of one-to-one relation: Vehicule.id ==> Biens.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    @JoinColumn(name = "numero_bien", nullable = false, unique = true)
    @MapsId
    @OneToOne(fetch = LAZY)
    public Biens getBiens() {
        return biens;
    }

    public void setBiens(Biens biens) {
        this.biens = biens;
    }

    public Vehicule biens(Biens biens) {
        setBiens(biens);
        return this;
    }

    /**
     * Apply the default values.
     */
    public Vehicule withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Vehicule && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Vehicule instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add(Vehicule_.id.getName(), getId()) //
                .add(Vehicule_.designationBien.getName(), getDesignationBien()) //
                .add(Vehicule_.immatriculation.getName(), getImmatriculation()) //
                .add(Vehicule_.numeroChassis.getName(), getNumeroChassis()) //
                .toString();
    }
}