/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 */
package com.artidev.oeildelynx.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Vehicule.class)
public abstract class Vehicule_ {

    // Raw attributes
    public static volatile SingularAttribute<Vehicule, Integer> id;
    public static volatile SingularAttribute<Vehicule, String> designationBien;
    public static volatile SingularAttribute<Vehicule, String> immatriculation;
    public static volatile SingularAttribute<Vehicule, String> numeroChassis;

    // Many to one
    public static volatile SingularAttribute<Vehicule, Modele> codeModele;
    public static volatile SingularAttribute<Vehicule, Type> codeType;
    public static volatile SingularAttribute<Vehicule, Couleur> codeCouleur;

    // One to one
    public static volatile SingularAttribute<Vehicule, Biens> biens;
}