/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/configuration/MessageSourceConfiguration.p.vm.java
 */
package com.artidev.oeildelynx.configuration;

import org.springframework.context.MessageSource;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.support.ReloadableResourceBundleMessageSource;

@Configuration
public class MessageSourceConfiguration {
    /**
     * Base message source to handle internationalization<b>
     * Order of basenames matters, the first found property is returned 
     */
    @Bean
    public MessageSource messageSource() {
        ReloadableResourceBundleMessageSource messageSource = new ReloadableResourceBundleMessageSource();
        messageSource.setFallbackToSystemLocale(false);
        messageSource.setUseCodeAsDefaultMessage(true);
        messageSource.setDefaultEncoding("UTF-8");
        messageSource.setBasenames( // 
                // main resources
                "classpath:/localization/application", "classpath:/localization/messages", //
                // pages
                "classpath:/localization/pages/home", //
                "classpath:/localization/pages/login", //
                "classpath:/localization/pages/concurrentModificationResolution", //
                // default spring security messages
                "classpath:org/springframework/security/messages", //
                //  our bean validation messages
                "classpath:ValidationMessages", //
                // default conversion messages
                "classpath:javax/faces/Messages", //
                // generated domain resources
                "classpath:/localization/domain/Affaire", //
                "classpath:/localization/domain/Arme", //
                "classpath:/localization/domain/Association30", //
                "classpath:/localization/domain/Association40", //
                "classpath:/localization/domain/AutreBien", //
                "classpath:/localization/domain/Biens", //
                "classpath:/localization/domain/BiensRecherches", //
                "classpath:/localization/domain/Biometrie", //
                "classpath:/localization/domain/Condamnation", //
                "classpath:/localization/domain/Contact", //
                "classpath:/localization/domain/Couleur", //
                "classpath:/localization/domain/Cpc", //
                "classpath:/localization/domain/Date", //
                "classpath:/localization/domain/Decouverte", //
                "classpath:/localization/domain/DecouverteDeBien", //
                "classpath:/localization/domain/DecouverteDePersonne", //
                "classpath:/localization/domain/Disparition", //
                "classpath:/localization/domain/EtabPenitencier", //
                "classpath:/localization/domain/Ethnie", //
                "classpath:/localization/domain/FamilleInfraction", //
                "classpath:/localization/domain/Genre", //
                "classpath:/localization/domain/ImageDeSceene", //
                "classpath:/localization/domain/Implications", //
                "classpath:/localization/domain/Indice", //
                "classpath:/localization/domain/Infraction", //
                "classpath:/localization/domain/Interpellation", //
                "classpath:/localization/domain/Jugement", //
                "classpath:/localization/domain/Juridiction", //
                "classpath:/localization/domain/ListeDetenus", //
                "classpath:/localization/domain/Localite", //
                "classpath:/localization/domain/Mandat", //
                "classpath:/localization/domain/Marque", //
                "classpath:/localization/domain/Modele", //
                "classpath:/localization/domain/Pays", //
                "classpath:/localization/domain/Personne", //
                "classpath:/localization/domain/Profession", //
                "classpath:/localization/domain/ProfilBiometrique", //
                "classpath:/localization/domain/ProfilPhoto", //
                "classpath:/localization/domain/Pv", //
                "classpath:/localization/domain/Race", //
                "classpath:/localization/domain/Recherche", //
                "classpath:/localization/domain/Region", //
                "classpath:/localization/domain/Religion", //
                "classpath:/localization/domain/ResidencePersonne", //
                "classpath:/localization/domain/SitMatrimoniale", //
                "classpath:/localization/domain/Type", //
                "classpath:/localization/domain/TypeArme", //
                "classpath:/localization/domain/TypeContact", //
                "classpath:/localization/domain/TypeMandant", //
                "classpath:/localization/domain/Unite", //
                "classpath:/localization/domain/Vehicule", //
                // default bean validation messages 
                "classpath:org/hibernate/validator/ValidationMessages" //
        );
        return messageSource;
    }
}
